input.onButtonPressed(Button.A, function () {
    basic.showString("A")
    pins.digitalWritePin(DigitalPin.P0, 1)
    music.ringTone(262)
    basic.pause(100)
    pins.digitalWritePin(DigitalPin.P0, 0)
    music.stopAllSounds()
    basic.pause(100)
    pins.digitalWritePin(DigitalPin.P0, 1)
    music.ringTone(262)
    basic.pause(500)
    pins.digitalWritePin(DigitalPin.P0, 0)
    music.stopAllSounds()
})
input.onButtonPressed(Button.B, function () {
    basic.showString("B")
    pins.digitalWritePin(DigitalPin.P0, 1)
    music.ringTone(262)
    basic.pause(500)
    pins.digitalWritePin(DigitalPin.P0, 0)
    music.stopAllSounds()
    basic.pause(100)
    for (let index = 0; index < 3; index++) {
        pins.digitalWritePin(DigitalPin.P0, 1)
        music.ringTone(262)
        basic.pause(100)
        pins.digitalWritePin(DigitalPin.P0, 0)
        music.stopAllSounds()
        basic.pause(100)
    }
})
